title: Your Awesome Class
author: Your Name
description: |
  Your awesome class in all it's glory.
keywords:
  - GDI
  - GDIMpls
  - Girl Develop It
  - Class
  - Awesome

# This is general info for GDIMpls
contact:
  name: GDI Minneapolis
  web: http://gdiminneapolis.com
  email: "minneapolis@girldevelopit.com"
  twitter: "gdimpls"
  github: "gdiminneapolis"


reveal_path: "/reveal.js"

# There are a handful of styles available with reveal. They can be found in the
# reveal.js/css/themes folder, and include:
#
# style: gdicool
# style: gdidefault
# style: gdilight
# style: gdisunny
# style: simple
style: gdidefault

# This is where your slides will be found, in the _slides/ folder.
# Number them in sequence
collections:
  - slides

exclude:
  - bin
  - CONTRIBUTOR_COVENANT.md
  - Description.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Outline.md
  - README.md

# Don't change these. Change values in _staging.yml and _publish.yml appropriately.
baseurl: ""
url: ""
